//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitaler_Ausbildungsbericht.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Digitaler_Ausbildungsbericht.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Anleitung___Digitaler_Ausbildungsbericht {
            get {
                object obj = ResourceManager.GetObject("Anleitung___Digitaler_Ausbildungsbericht", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;style type=&quot;text/css&quot;&gt;
        ///body {
        ///	background-color:#7D7D7D;
        ///}
        ///&lt;/style&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;form action=&quot;https://www.paypal.com/cgi-bin/webscr&quot; method=&quot;post&quot; target=&quot;blank&quot;&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;cmd&quot; value=&quot;_s-xclick&quot;&gt;
        ///&lt;input type=&quot;hidden&quot; name=&quot;hosted_button_id&quot; value=&quot;649SVR8X3JWEA&quot;&gt;
        ///&lt;table&gt;
        ///&lt;tr&gt;&lt;select name=&quot;os0&quot;&gt;
        ///	&lt;option value=&quot;Kleine Spende&quot;&gt;Kleine Spende €5,00 EUR&lt;/option&gt;
        ///	&lt;option value=&quot;Mittlere Spende&quot;&gt;Mittlere Spende €10,00 EUR&lt;/option&gt;
        ///	&lt;option value=&quot;Große Spende&quot;&gt;G [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;style type=&quot;text/css&quot;&gt;
        ///body {
        ///	background-color:#535353;
        ///}
        ///#fbLikeIframe{
        ///	position: absolute;
        ///	top:0px;
        ///	left:0px;
        ///	background-color:#535353;
        ///}
        ///&lt;/style&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;iframe src=&quot;http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fausbildungsbericht.net%2F&amp;amp;layout=button_count&amp;amp;show_faces=true&amp;amp;width=300&amp;amp;height=25&amp;amp;action=like&amp;amp;font=arial&amp;amp;colorscheme=light&quot; id=&quot;fbLikeIframe&quot; name=&quot;fbLikeIframe&quot; allowtransparency=&quot;true&quot; class=&quot;fbLikeContainer&quot; st [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FBLike {
            get {
                return ResourceManager.GetString("FBLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;style type=&quot;text/css&quot;&gt;
        ///body {
        ///	background-color:#535353;
        ///}
        ///#I1_1313682162441{
        ///	position: absolute;
        ///	top:0px;
        ///	left:0px;
        ///	background-color:#535353;
        ///	padding-top:-10px;
        ///}
        ///&lt;/style&gt;
        ///&lt;iframe allowtransparency=&quot;true&quot; hspace=&quot;0&quot; id=&quot;I1_1313682162441&quot; marginheight=&quot;0&quot; marginwidth=&quot;0&quot; name=&quot;I1_1313682162441&quot; src=&quot;https://plusone.google.com/u/0/_/+1/fastbutton?url=http%3A%2F%2Fausbildungsbericht.net&amp;amp;size=medium&amp;amp;count=true&amp;amp;annotations=&amp;amp;hl=de&amp;amp;jsh=r%3Bgc%2F23123384-f8bf5791#id=I1_1313682 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Googleplus {
            get {
                return ResourceManager.GetString("Googleplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon iconLarge {
            get {
                object obj = ResourceManager.GetObject("iconLarge", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon iconSmall {
            get {
                object obj = ResourceManager.GetObject("iconSmall", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenz
        ///
        ///DER GEGENSTAND DIESER LIZENZ (WIE UNTER &quot;SCHUTZGEGENSTAND&quot; DEFINIERT) WIRD UNTER DEN BEDINGUNGEN DIESER CREATIVE COMMONS PUBLIC LICENSE (&quot;CCPL&quot;, &quot;LIZENZ&quot; ODER &quot;LIZENZVERTRAG&quot;) ZUR VERFÜGUNG GESTELLT. DER SCHUTZGEGENSTAND IST DURCH DAS URHEBERRECHT UND/ODER ANDERE GESETZE GESCHÜTZT. JEDE FORM DER NUTZUNG DES SCHUTZGEGENSTANDES, DIE NICHT AUFGRUND DIESER LIZENZ ODER DURCH GESETZE GESTATTET IST, IST UNZULÄSSIG.
        ///
        ///DURCH DIE AUSÜBUNG EINES DURCH DIESE LIZENZ GEWÄHRTEN RECHTS AN DEM SCHUTZGEGENSTAND ER [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Erheben, Speichern und Veröffentlichen von anonymen Daten zu Analysezwecken
        ///
        ///Folgend sind Aktionen aufgelistet, bei denen unser Programm eine Verbindung zu unserem Server aufbaut:
        ///- Beim Starten des Programms
        ///- Beim Speichern einer Woche als PDF
        ///- Bei der Benutzung der Programmbewertung
        ///- Beim Senden von Feedback
        ///
        ///9.a Wahrung Ihrer Anonymität
        ///
        ///Im Zuge dieser Verbindung wird ihre IP-Adresse zwar an unseren Server übertragen, jedoch werden vor Speicherung in unserem System
        ///die letzten 8 Bit dies [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string privacypolicy {
            get {
                return ResourceManager.GetString("privacypolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SET SQL_MODE=&quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        ////*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        ////*!40101 SET NAMES utf8 */;
        ///
        ///--
        ///-- Datenbank: `reportbackups`
        ///--
        ///CREATE DATABASE `reportbackups` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
        ///USE `reportbackups`;
        ///
        ///--
        ///-- Tabellenstruktur für Tabelle `reports`
        ///--
        ///
        ///DROP TABLE IF EXISTS `reports`;
        ///
        ///CREATE TABLE IF  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string sqlHeader {
            get {
                return ResourceManager.GetString("sqlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;form action=&quot;https://www.paypal.com/cgi-bin/webscr&quot; method=&quot;post&quot;&gt; ähnelt.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;input type=&quot;hidden&quot; name=&quot;cmd&quot; value=&quot;_s-xclick&quot;&gt; ähnelt.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/table&gt; ähnelt.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;input type=&quot;hidden&quot; name=&quot;currency_code&quot; value=&quot;EUR&quot;&gt; ähnelt.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;input type=&quot;image&quot; src=&quot;http://ausbildungsbericht.net/paypal_donate.gif&quot; border=&quot;0&quot; name=&quot;submit&quot; alt=&quot;Jetzt einfach, schnell und sicher online bezahlen – mit PayPal.&quot;&gt; ähnelt.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;img alt=&quot;&quot; border=&quot;0&quot; src=&quot;https://www.paypalobjects.com/de_DE/i/scr/pixel.gif&quot; width=&quot;1&quot; height=&quot;1&quot;&gt; ähnelt.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/form&gt; ähnelt.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;input type=&quot;hidden&quot; name=&quot;hosted_button_id&quot; value=&quot;649SVR8X3JWEA&quot;&gt; ähnelt.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;table&gt; ähnelt.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;tr&gt;&lt;td&gt;&lt;input type=&quot;hidden&quot; name=&quot;on0&quot; value=&quot;Spenden&quot;&gt;Spenden&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;select name=&quot;os0&quot;&gt; ähnelt.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;option value=&quot;Kleine Spende&quot;&gt;Kleine Spende €5,00 EUR&lt;/option&gt; ähnelt.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;option value=&quot;Mittlere Spende&quot;&gt;Mittlere Spende €10,00 EUR&lt;/option&gt; ähnelt.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;option value=&quot;Große Spende&quot;&gt;Große Spende €25,00 EUR&lt;/option&gt; ähnelt.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;option value=&quot;XXL Spende&quot;&gt;XXL Spende €50,00 EUR&lt;/option&gt; ähnelt.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/select&gt; &lt;/td&gt;&lt;/tr&gt; ähnelt.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] Updater {
            get {
                object obj = ResourceManager.GetObject("Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
